### PR TITLE
feat: rtl support

### LINKED ISSUE #298: support rtl
thanks for this fine component,

but when I tried horizontal scrolling while in rtl mode, it simply didn't work

by setting `<html dir="rtl">` it shows white empty space.

please fix it so I can use it in my app

much appreciated

### PR DESCRIPTION
**Pull request by NoamBuzaglo**
Hey,
I opened this pull request to add rtl support to the horizontal scroller.
resolve #298

### CODE REVIEW

**Comment by NoamBuzaglo** [comment]
#298

**Comment by NoamBuzaglo** [comment]
@speige @rintoj

**Comment by NoamBuzaglo** [comment]
@whyboris

**Comment by whyboris** [comment]
This looks like a good contribution!

**Comment by speige** [comment]
Sorry, I've been away for awhile.
Thanks for the contribution!

I merged a few other PRs that had indentation changes, because I was too lazy to ask them to fix it. I think that caused some conflicts in your PR. Could you fix that?

Also, could you update the readme with instructions on how to use this?

Also, could you update the demo with an example of it in use?
We use the demo for testing during each release to make sure we don't accidentally break any supported features.

Thanks!

**Comment by NoamBuzaglo** [comment]
Hey, thank you i will update you when i will complete your requests.

בתאריך יום ד׳, 26 בפבר׳ 2020, 19:46, מאת Devin Garner ‏<
notifications@github.com>:

**Comment by NoamBuzaglo** [comment]
> Sorry, I've been away for awhile.
> Thanks for the contribution!
> 
> I merged a few other PRs that had indentation changes, because I was too lazy to ask them to fix it. I think that caused some conflicts in your PR. Could you fix that?
> 
> Also, could you update the readme with instructions on how to use this?
> 
> Also, could you update the demo with an example of it in use?
> We use the demo for testing during each release to make sure we don't accidentally break any supported features.
> 
> Thanks!



> Sorry, I've been away for awhile.
> Thanks for the contribution!
> 
> I merged a few other PRs that had indentation changes, because I was too lazy to ask them to fix it. I think that caused some conflicts in your PR. Could you fix that?
> 
> Also, could you update the readme with instructions on how to use this?
> 
> Also, could you update the demo with an example of it in use?
> We use the demo for testing during each release to make sure we don't accidentally break any supported features.
> 
> Thanks!

I did what you asked, this PR is ready to merge.
Thanks.

**Comment by speige** [comment]
This is now live in npm under v4.0.1

**Pull request merged**
