### PR TITLE
fix(virtual-scroller): added flag to run update calculations outside …

### PR DESCRIPTION
**Pull request by nickbullock**
…zone

also:
- added script debugDemo script for mac users
- updated readme about new flag

thoughts:
i was thinking about how to implement this feature without flag and i can see two ways:
- to find parent of any type and run change detection manually. This way led me to a dead end and all i found is how to get parent component (very dirty): this.viewContainerRef.injector.view.component. And then find/inject cdr and call detectChanges
- to run RAF and listeners inside runOutsideAngular, but call vsUpdate.emit inside zone (but without zone.run / appRef.tick / etc). This way looks well, but idk how to implement it right now

ps. can't revert line separators of dist/virtual-scroller.d.ts. omg

### CODE REVIEW

**Comment by sharikovvladislav** [comment]
Fixes #240

**Comment by sharikovvladislav** [comment]
@speige any thoughts on this?

**Comment by sharikovvladislav** [comment]
@speige I ll create some example on stackblitz to show issue with zone.run. We are influenced by this stuff a lot. 

I ll do it on the weekend or at Monday.

**Comment by sharikovvladislav** [comment]
> I'm not sure I understand the benefits to this PR. Maybe we need to keep brainstorming?

@speige here is it. I found some time now. Really easy to reproduce.

https://stackblitz.com/edit/angular-virtual-scroller-problem-cuz-of-zone-run

Here is the example. I use version of virtual-scroller from this PR. Now `[shouldUpdateRunInZone]` set to false. You can see how smooth and fast the list is. 

Change this to true. You will see how behavior is changed. Now you can see some lags.

Of course this is rather synthetic test. But this is something like we see in our application.

**Comment by sharikovvladislav** [comment]
> Your suggestion is to use this code

This code was suggested because we need some callback to call `detectChanges` after virtual scroller emits new value and we set items. And in case of that callback it is more explicit to use additional value (as I think). But thats not the main point of that PR. We need perfomance :) mostly

**Comment by sharikovvladislav** [comment]
Also, don't merge this PR, please. Let us finish some tests in our real application. If it is possible.

**Comment by sharikovvladislav** [comment]
Yep. We can do this but it is huge BC. I asked my colleague to check
performance with that change. If evetything is ok i Will message you

Thabk you!
пт, 5 окт. 2018 г. в 22:26, Devin Garner <notifications@github.com>:

**Comment by speige** [comment]
This PR looks the same as it did 6 days ago. Did you change something that I missed?

I'm happy with the performance improvement. But, I still wonder if we should avoid adding a new flag & instead *always* run outside zone & automatically call detectChanges on the virtual-scroller parent cdr. Even if it's "bad code" it's hidden inside our component & it's nice for the consuming applications to get the speedup for free without having to rewrite their code.

Thoughts?

Let's research this a bit longer before we make a final decision. Worst case scenario I'll merge the PR as is, but if we can make it a slightly smoother upgrade process, that's my preference. I'll play around with this & see if I can come up with anything.

**Comment by speige** [comment]
I think I found something:
```
@SkipSelf() protected readonly parentChangeDetectorRef: ChangeDetectorRef,
```

I'm going to try to merge your PR, but use this instead of the flag & see how it goes.

**Comment by speige** [comment]
I merged this & released it to npm under version 1.0.8. @SkipSelf() seemed to work, so I removed the flag & made it always avoid zone.run & also automatically call detect changes on the parent. Hopefully this change was okay. Let me know how it works for you & if you have any issues with it.

Thanks for your contribution! Please continue to submit PRs as you have ideas :)

**Comment by speige** [comment]
I found a problem with this related to ChangeDetectionStrategy.OnPush, which I discussed in issue #240 
For now I'm putting it behind a flag. If we find a fix for this side-effect we can remove the flag.

**Comment by sharikovvladislav** [comment]
> I think I found something:
> 
> ```
> @SkipSelf() protected readonly parentChangeDetectorRef: ChangeDetectorRef,
> ```
> I'm going to try to merge your PR, but use this instead of the flag & see how it goes.

I am not sure this will work.

The problem is with content projection. We have a bit more complex nesting of the components. Let me check

**Comment by sharikovvladislav** [comment]
Looks like we have the ability to do same stuff as we did with our version of the code. Let us check. We need some time.

**Comment by speige** [comment]
I've released a new version to npm 1.0.10 which uses your original PR (without parentChangeDetectorRef.detectChanges). I renamed the flag to executeRefreshOutsideAngularZone. 

Please let me know if that doesn't resolve your issue.

I added a warning in the readme about why I think using the flag is a bad idea. Hopefully I wasn't too harsh. Also, hopefully my facts were correct, because I don't completely understand Angular ChangeDetection. Without the warning I'm afraid too many users would think it was an easy/free performance boost & then I'd have to response to a lot of issues about their apps being broken.

I apologize if I made the PR experience frustrating. You understand ChangeDetection much better than me :) I'm very thankful for your help. Please continue to contribute.

**Pull request merged**
