### PR TITLE
Fixes unlimeted scroll issue

### PR DESCRIPTION
**Pull request by MBcom**
This PR targets #68 . Currently ngx-virtual-scroller uses the height property to display the browser scroll bars. But for many records (where the usage of ngx-virtual-scroller makes sense) the maxmimum height is overstepped and firefox defaults to 0. So scrolling stops working.

In this PR I switched over to use transform scaleY/X Properties instead of the height property for the "hidden" container/div. They are not limited and so scrolling works even for millions of records.

### CODE REVIEW

**Comment by JoMas971** [comment]
Helo,

I was curious about your solution, but i can't actually see what you've changed... It seems the same than the master version...

**Comment by MBcom** [comment]
@JoMas971 sry I opened the pull request some months after i did the changes - so I mixed up translate and scale  
the important changes are https://github.com/rintoj/ngx-virtual-scroller/blob/dfad6e5945ce7031edfc6d255244841401e3ab85/src/virtual-scroller.ts#L658 ,
https://github.com/rintoj/ngx-virtual-scroller/blob/dfad6e5945ce7031edfc6d255244841401e3ab85/src/virtual-scroller.ts#L667 and https://github.com/rintoj/ngx-virtual-scroller/blob/dfad6e5945ce7031edfc6d255244841401e3ab85/src/virtual-scroller.ts#L787.  
  
the changed identation cames from my ide - sry for this

**Comment by speige** [comment]
Sorry, I've been away for awhile.

Thanks for the contribution!

Could you correct the indentation issues & merge conflicts? It'll make it much easier to accept the PR if github only shows the actual lines that changed.

Thanks!

**Comment by MBcom** [comment]
@speige  
done

**Comment by speige** [comment]
There seem to be bugs with this PR.

1st)
an invalid transform syntax is causing the style to not be applied

image

transform: scaleX(17250000px) // invalid due to px
transform: scaleX(7250000) // valid

This may have been an accident due to merge conflicts, because it looks like you removed the px in a previous commit and then re-added it in a later commit.

2nd) The behavior of the scrollbars doesn't work correctly in the new version.
Working "live" demo at https://rintoj.github.io/ngx-virtual-scroller/samples
image
Notice the scrollbar "thumb" is very small, because the viewport is only 6 out of 10,000 records.

image
Notice the scrollbar "thumb" is very big, which is incorrect.


Let me know if I'm doing something wrong. I'm happy to accept the PR if we can get it working correctly.

**Comment by MBcom** [comment]
should work now

**Pull request merged**
